<%@ page language="java" import="java.io.File, java.util.ArrayList,java.util.Scanner, java.io.*,java.util.Random, java.net.*, java.util.Vector, common.*,common.Utility,common.User" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>

<jsp:include page="head.jsp" />

<body>
<div class="main" style="">
	<h1 style="    text-align: center;">Examples of Natural Language Descriptions</h1>
		
		
<p class="box" style="margin:20px;width:90%">  
		To train yourself in using NLG, please spend a little bit of time with the two examples that follow. In each case, there is a natural language description and two questions.
		
		Try to find the information to answer the questions. Click on the question to see if the information you found is correct.<br>
		After you finish exploring the examples, click on Continue button to go to the proper evaluation.
</p>

<script src="nlg/html5ext.js" type="text/javascript"></script>
	<div style="width:100%;;;;margin:10px;"> 
	
		<h3>Example of NLG 1:</h3>   
            <div style="width:450px;background:white; overflow: hidden;">					
            <div id=nlg1 style="     color: black;font-size: 16px;padding: 10px;float:left;height:100%;"></div>
				<script type="text/javascript">
				$(document).ready(function(){
					$.ajax({
						type: 'GET',
						url: "/ourspaces/LiberRestServlet?resourceID=" + "<%=URLEncoder.encode("http://openprovenance.org/ontology#0013a70e-715d-43d6-9a4c-938deb7dbd76","UTF-8")%>&Property=provenance", 
						dataType : "html",
						async : false,
						success : function(html, errorThrown) {
							$("div#nlg1").html(html);
						}
					});
				});
				</script>
			</div>
		
		<div id="q1body" style="" class="questionBody">		
			<h4 style="text-align: left;"><a style="color:white" href="#" onclick="$('#q2answer').toggle();return false;">Who was examining the scan image?</a></h4>
			<p style="display: none;margin:20px;width:90%" id="q2answer">We can see the description of an artifact Lisa's Diagnosis Report - it was generated by the process Examination of Brain Scan Image. Click on the process name in order to find more about it. Now we can see that the process was controlled by two doctors - the correct answer is Doctor Joe Bloggs and  Doctor Melinda Carpenter.</p>
		</div>
		<div id="q1body" style="" class="questionBody">		
			<h4 style="text-align: left;"><a style="color:white" href="#" onclick="$('#q1answer').toggle();return false;">What is the name of the patient involved in the MRI Scan Process?</a></h4>
			<p style="display: none;margin:20px;width:90%" id="q1answer">Let's explore the provenance of the artifact Scan image. It was generated by the process MRI Scan. After expanding the process, we can see two agents - one was controlling the process and the other was involved in it. The "was controlled by" edge denotes a controlling agent, in this case a doctor. Involved, on the other hand, denotes a passive agent, a patient. The name of the patient is therefore Lisa Peterson.</p>
		</div>
		
	</div>
	
	 <div style="width:100%;;;;margin:10px;"> 
		<h3>Example of NLG 2:</h3>   
            <div style=";;;width:300px;background:white;height: 100%;  overflow: hidden;">
            <div id=nlg2 style="     color: black;font-size: 16px;padding: 10px;float:left;height:100%;"></div>
				<script type="text/javascript">
				$(document).ready(function(){
					$.ajax({
						type: 'GET',
						url: "/ourspaces/LiberRestServlet?resourceID=" + "<%=URLEncoder.encode("http://openprovenance.org/ontology#dd34c9fe-5dc3-4b59-a71e-54328fd62119","UTF-8")%>&Property=provenance", 
						dataType : "html",
						async : false,
						success : function(html, errorThrown) {
							$("div#nlg2").html(html);
						}
					});
				});
				</script></div>		
		<div id="q3body" style="" class="questionBody">		
			<h4 style="text-align: left;"><a style="color:white" href="#" onclick="$('#q3answer').toggle();return false;">Who developed the Weka software?</a></h4>
			<p style="display: none;margin:20px;width:90%" id="q3answer">When you expand the artifact Weka software and the process Weka development, you can see three agents controlling the process. The developers are Eibe Frank, Mark Hall and Len Trigg.</p>
		</div>
						<div id="q4body" style="" class="questionBody">		
			<h4 style="text-align: left;"><a style="color:white" href="#" onclick="$('#q4answer').toggle();return false;">How many artefacts did the process Simulation run use?</a></h4>
			<p style="display: none;margin:20px;width:90%" id="q4answer">After expanding artifact Simulation output, you can see the process Simulation run. After expanding it, there are two artefacts used by it - Configuration 1 and Simulation software.</p>
		</div>
	</div>
	
	<form action="send.jsp"  METHOD="POST">
	
    <INPUT name="id" TYPE="hidden" VALUE="nlgintro">
    <INPUT name="type" TYPE="hidden" VALUE="-1">
    <INPUT name="dataset" TYPE="hidden" VALUE="examples">
    <INPUT id="time" name="time" TYPE="hidden" VALUE="0">
    <INPUT onclick="var time = new Date().getTime() - start;$('#time').val(time);return true;" style="cursor: pointer;text-decoration: underline;background-color: darkblue;border: 0 none;border-radius: 5px 5px 5px 5px;color: white;float: left;font-family: times;font-size: 14px;padding: 10px;" TYPE="SUBMIT" VALUE="Continue">
    </form> 
<!--  	<a onclick="sendResults();return true;" style="color:white;" href="Task.jsp"><span style="border-radius:5px;padding:10px;background-color:darkblue;display: block; padding: 10px; width: 130px;;">Continue to the task</span></a>
-->
</div>

<script>
$(document).ready(function(){
	$(".nlg").each(function(){
		var nlgitem=this;
		//Check if the NLG is already bound

		if(typeof $(nlgitem).data("events") != "undefined"
			&& typeof $(nlgitem).data("events").mouseover != "undefined"
			&& $(nlgitem).data("events").mouseover.length >= 1){
			for(var x in $(nlgitem).data("events").mouseover){
				if($(nlgitem).data("events").mouseover[x].namespace.substring(0,4)=="qtip")
					return;
			}
		}
		/*if(typeof $(nlgitem).data("events") != "undefined"
			&& typeof $(nlgitem).data("events").mouseover != "undefined"
			&& $(nlgitem).data("events").mouseover.length >= 2
			&& $(nlgitem).data("events").mouseover[1].namespace.substring(0,4)=="qtip")
			return;*/

	   $(this).qtip({
		   content: 'Some basic content for the tooltip',
	   hide: {
           fixed: true // Make it fixed so it can be hovered over
        },
       position: { adjust: { x: -10, y: -10 } },
	   style: {
           padding: '10px', // Give it some extra padding
           //name: 'cream',
           tip: { color: 'black' } 
        },
        api: {
	         // Retrieve the content when tooltip is first rendered
	         onRender: function()
	         {
	        	
	        	
	        	
	        	var self = this;
            $.ajax({
				type: 'GET',
				url: '/ourspaces/LiberRestServlet', 
				data: { resourceID: $(nlgitem).attr("rel") },
				dataType : "html",
				async : false,
				success : function(str, errorThrown) {
					
					
					self.updateContent(str);
				}
			});
            annotateTerms();
	         }
	         }
	});
	   var y = 0;
	   
});

	$("a.liber2").live('click',function() {
		var anchor = this;
		var did = $(this).attr("rel");

		// if the div containing the text hasn't been set yet:
		if( $("div#"+did).is(':empty') ) {

			// call LiberRestServlet to obtain the textual description of the resource:
			$.ajax({
				type: 'GET',
				url: $(this).attr("href"), 
				dataType : "html",
				async : false,
				success : function(html, errorThrown) {
					$("div#"+did).html(html);
					$("div#"+did).hide();
					return false;
				}
			});
		}
		
		// show/hide the text:
		$("div#"+did).slideToggle("fast");
		return false;
	});
});



function sendResults(){
	var jsonOb = new Object();
	jsonOb.time = new Date().getTime() - start;
	jsonOb.id = "nlgintro";
	jsonOb.type="-1";
	jsonOb.dataset = "intro";
	var jsonString = JSON.stringify(jsonOb);
	$.post("/ourspaces/provVisEvaluation/send.jsp",{data:jsonString},
			  function(data2) {
			}
	);
	return true;
}
$(document).ready(function(){
	jQuery.ajaxSetup({
		async : false
	});
	start = new Date().getTime();
});
</script> 
</body>
</html>