/* CVS $Id: $ */
package org.policygrid.ontologies; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from file:/Applications/Protege_3.4/schemagen-temp.owl 
 * @author Auto-generated by schemagen on 17 Aug 2009 15:23 
 */
public class Utility {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.policygrid.org/utility.owl#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>General information</p> */
    public static final ObjectProperty hasAddress = m_model.createObjectProperty( "http://www.policygrid.org/utility.owl#hasAddress" );
    
    /** <p>xxx</p> */
    public static final ObjectProperty hasDepartment = m_model.createObjectProperty( "http://www.policygrid.org/utility.owl#hasDepartment" );
    
    /** <p>xxx</p> */
    public static final ObjectProperty hasEmployee = m_model.createObjectProperty( "http://www.policygrid.org/utility.owl#hasEmployee" );
    
    /** <p>xxx</p> */
    public static final DatatypeProperty country = m_model.createDatatypeProperty( "http://www.policygrid.org/utility.owl#country" );
    
    /** <p>xxx</p> */
    public static final DatatypeProperty houseNumber = m_model.createDatatypeProperty( "http://www.policygrid.org/utility.owl#houseNumber" );
    
    /** <p>General information</p> */
    public static final DatatypeProperty name = m_model.createDatatypeProperty( "http://www.policygrid.org/utility.owl#name" );
    
    /** <p>xxx</p> */
    public static final DatatypeProperty place = m_model.createDatatypeProperty( "http://www.policygrid.org/utility.owl#place" );
    
    /** <p>xxx</p> */
    public static final DatatypeProperty postcode = m_model.createDatatypeProperty( "http://www.policygrid.org/utility.owl#postcode" );
    
    /** <p>xxx</p> */
    public static final DatatypeProperty street = m_model.createDatatypeProperty( "http://www.policygrid.org/utility.owl#street" );
    
    /** <p>General information</p> */
    public static final DatatypeProperty telephoneNumber = m_model.createDatatypeProperty( "http://www.policygrid.org/utility.owl#telephoneNumber" );
    
    public static final OntClass Address = m_model.createClass( "http://www.policygrid.org/utility.owl#Address" );
    
    public static final OntClass Department = m_model.createClass( "http://www.policygrid.org/utility.owl#Department" );
    
    public static final OntClass Organisation = m_model.createClass( "http://www.policygrid.org/utility.owl#Organisation" );
    
}
