<%@ page language="java" import="java.util.Iterator, java.util.ArrayList, java.io.*, java.net.*, java.util.Vector, common.*" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
    
<% User user = new User(); 

user = (User) session.getAttribute("use");
if (user.getID() == 0)
	response.sendRedirect(response.encodeRedirectURL("/error.jsp"));
%>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>ourSpaces</title>
<link rel="stylesheet" type="text/css" href="style.css" />

<script type="text/javascript" src="includes/prototype.js"></script>
<script type="text/javascript" src="javascript/tab.js"></script>
<script type="text/javascript" src="javascript/jquery-1.2.6.min.js"></script>
<link href="facebox.css" media="screen" rel="stylesheet" type="text/css"/>
<script src="facebox.js" type="text/javascript"></script> 

<script type="text/javascript" language="javascript">
jQuery(document).ready(function($) {
  $('a[rel*=facebox]').facebox()
}) 
</script>

<script language="javascript" type="text/javascript">
function stopRKey(evt) {
   var evt = (evt) ? evt : ((event) ? event : null);
   var node = (evt.target) ? evt.target : ((evt.srcElement) ? evt.srcElement : null);
   if ((evt.keyCode == 13) && (node.type=="text")) {return false;}
}
document.onkeypress = stopRKey;
-->
</script>

<script language="javascript">

  
function checkform()
{
	if (!document.getElementById('agree').checked)
	{
		alert('You must accept the Terms and Condition before continuing to use ourSpaces.');
		return false;
	} 
	
	return true;
}

</script>

<link rel="stylesheet" type="text/css" href="style.css" />

</head>

<body>

<div class="header">
	<div class="headerIndexLogo"></div>
</div>
<div class="indexBG">
	<div class="indexCenterPanel">
    	<div class="indexCenterPanelText">
        	<p style="margin-bottom:10px; color:#990000;" align="center">Attention: You have not accepted our Terms and Conditions policy.</p>
        	<textarea style="width:350px; height:150px;">
ourSpaces is a Virtual Research Environment (VRE) developed by the University of Aberdeen as part of the PolicyGrid II research project. PolicyGrid is supported by the Economic and Social Research Council, project number: RES-149-25-1075.

PolicyGrid II is a research project examining interdisciplinary research and developing computational tools to support interdisciplinary research teams. As such we will be exploring the ways in which interdisciplinary research teams communicate and co-operate via ourSpaces. 
				
We make use of the data generated by users (for example; meta-tagging, user interactions) only to support the academic research of PolicyGrid II. Selected elements of this research project may be subject to additional approval; we will seek consent from associated participants as appropriate. 
				
Data that you upload into ourSpaces is stored securely; our servers are located in a secure environment and server administration is handled only by members of University of Aberdeen staff working on the PolicyGrid II project. We strongly recommend that you keep alternative copies of your data as we will not be liable for loss or damage to data while it is stored within our systems. 
				
Data resources which you upload can be made private or public; private resources are inaccessible to all but the owner and any additional members who the owner permits access.
				
ourSpaces must not be used for any commercial purpose whatsoever or for any illegal or unauthorised purpose. When you use ourSpaces you must comply with all applicable UK laws relating to online conduct (including, without limitation, content which can be posted online) and with any applicable international laws, including the local laws in your country of residence.
				
All user profiles are public on ourSpaces and therefore can be viewed by any registered member. Any person can become a registered member simply by completing the registration process and agreeing to these terms and conditions.
				
You may remove your profile and content at any time however it is important to be aware that we may be unable to delete certain elements related to uploaded content, for example commentary relating to a document cannot be removed but will instead be anonymised.  
				
This service complies with the University of Aberdeen - Policy on Data Protection (http://www.abdn.ac.uk/hr/uploads/files/data%20protection.pdf) and is governed by the University of Aberdeen - Conditions for using IT Facilities (http://www.abdn.ac.uk/dit/documents/cond-IT.pdf).

Note: please contact info@ourspaces.net if you wish to use ourSpaces but do not wish to be included in our research.
</textarea>
    	<p style="margin-bottom:10px; margin-top:10px; font-size:10px;">
		Please contact us if you have any queries about our terms or our privacy policy. 
	</p>
	
	<form method="post" action="Controller?action=confirmTC" onSubmit="return checkform()">
	
	<p style="margin-bottom:10px; color: #FF6600;">
		<input type="checkbox" name="agree" id="agree"> I agree to the Terms and Conditions <br><br>
	</p>    	
        	
    
                <p style="margin-top:5px; margin-left:85px;">
                	<input type="image" src="images/continue.png"  id="submitForm" />
                </p>
    </form>
            </div>
    	</div>
    </div>
</div>




</body>
</html>

	